#pragma once 

/* --- VREFBUF: VREFBUF --------------------------------------------- */

/** @defgroup vrefbuf_registers VREFBUF Register
@{*/

/** VREFBUF_CSR VREFBUF control and status register **/
#define VREFBUF_CSR			MMIO32(VREFBUF_BASE + 0x00)
/** VREFBUF_CCR VREFBUF calibration control register **/
#define VREFBUF_CCR			MMIO32(VREFBUF_BASE + 0x04)

/**@}*/


/** @defgroup vrefbuf_csr CSR VREFBUF control and status register
@{*/


#define VREFBUF_CSR_VRS_SHIFT		4
#define VREFBUF_CSR_VRS_MASK		0x07
/** @defgroup vrefbuf_csr_vrs VRS Voltage reference scale These bits select the value generated by the voltage reference buffer. Other: Reserved
@{*/
/**@}*/

/** VREFBUF_CSR_VRR Voltage reference buffer ready **/
#define VREFBUF_CSR_VRR		(1 << 3)
/** VREFBUF_CSR_HIZ High impedance mode This bit controls the analog switch to connect or not the VREF+ pin. Refer to Table196: VREF buffer modes for the mode descriptions depending on ENVR bit configuration. **/
#define VREFBUF_CSR_HIZ		(1 << 1)
/** VREFBUF_CSR_ENVR Voltage reference buffer mode enable This bit is used to enable the voltage reference buffer mode. **/
#define VREFBUF_CSR_ENVR		(1 << 0)

/**@}*/

/** @defgroup vrefbuf_ccr CCR VREFBUF calibration control register
@{*/


#define VREFBUF_CCR_TRIM_SHIFT		0
#define VREFBUF_CCR_TRIM_MASK		0x3f
/** @defgroup vrefbuf_ccr_trim TRIM Trimming code These bits are automatically initialized after reset with the trimming value stored in the Flash memory during the production test. Writing into these bits allows to tune the internal reference buffer voltage.
@{*/
/**@}*/


/**@}*/
