#pragma once 

/* --- LOCKBIT:  ---------------------------------------------------- */

/** @defgroup lockbit_registers None Register
@{*/

/** LOCKBIT_LOCKBIT_WORD0 Lock Bits Word 0 **/
#define LOCKBIT_LOCKBIT_WORD0			MMIO32(LOCKBIT_BASE + 0x00)

/**@}*/


/** @defgroup lockbit_lockbit_word0 LOCKBITWORD0 Lock Bits Word 0
@{*/

/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_31 Lock Region 31 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_31		(1 << 31)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_30 Lock Region 30 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_30		(1 << 30)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_29 Lock Region 29 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_29		(1 << 29)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_28 Lock Region 28 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_28		(1 << 28)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_27 Lock Region 27 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_27		(1 << 27)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_26 Lock Region 26 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_26		(1 << 26)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_25 Lock Region 25 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_25		(1 << 25)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_24 Lock Region 24 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_24		(1 << 24)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_23 Lock Region 23 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_23		(1 << 23)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_22 Lock Region 22 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_22		(1 << 22)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_21 Lock Region 21 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_21		(1 << 21)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_20 Lock Region 20 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_20		(1 << 20)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_19 Lock Region 19 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_19		(1 << 19)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_18 Lock Region 18 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_18		(1 << 18)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_17 Lock Region 17 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_17		(1 << 17)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_16 Lock Region 16 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_16		(1 << 16)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_15 Lock Region 15 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_15		(1 << 15)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_14 Lock Region 14 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_14		(1 << 14)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_13 Lock Region 13 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_13		(1 << 13)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_12 Lock Region 12 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_12		(1 << 12)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_11 Lock Region 11 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_11		(1 << 11)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_10 Lock Region 10 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_10		(1 << 10)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_9 Lock Region 9 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_9		(1 << 9)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_8 Lock Region 8 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_8		(1 << 8)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_7 Lock Region 7 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_7		(1 << 7)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_6 Lock Region 6 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_6		(1 << 6)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_5 Lock Region 5 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_5		(1 << 5)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_4 Lock Region 4 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_4		(1 << 4)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_3 Lock Region 3 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_3		(1 << 3)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_2 Lock Region 2 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_2		(1 << 2)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_1 Lock Region 1 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_1		(1 << 1)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_0 Lock Region 0 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_0		(1 << 0)

/**@}*/
