#pragma once 

/* --- LOCKBIT:  ---------------------------------------------------- */

/** @defgroup lockbit_registers None Register
@{*/

/** LOCKBIT_LOCKBIT_WORD0 Lock Bits Word 0 **/
#define LOCKBIT_LOCKBIT_WORD0			MMIO32(LOCKBIT_BASE + 0x00)
/** LOCKBIT_LOCKBIT_WORD1 Lock Bits Word 1 **/
#define LOCKBIT_LOCKBIT_WORD1			MMIO32(LOCKBIT_BASE + 0x04)
/** LOCKBIT_LOCKBIT_WORD2 Lock Bits Word 2 **/
#define LOCKBIT_LOCKBIT_WORD2			MMIO32(LOCKBIT_BASE + 0x08)
/** LOCKBIT_LOCKBIT_WORD3 Lock Bits Word 3 **/
#define LOCKBIT_LOCKBIT_WORD3			MMIO32(LOCKBIT_BASE + 0x0c)

/**@}*/


/** @defgroup lockbit_lockbit_word0 LOCKBITWORD0 Lock Bits Word 0
@{*/

/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_31 Lock Region 31 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_31		(1 << 31)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_30 Lock Region 30 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_30		(1 << 30)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_29 Lock Region 29 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_29		(1 << 29)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_28 Lock Region 28 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_28		(1 << 28)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_27 Lock Region 27 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_27		(1 << 27)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_26 Lock Region 26 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_26		(1 << 26)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_25 Lock Region 25 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_25		(1 << 25)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_24 Lock Region 24 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_24		(1 << 24)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_23 Lock Region 23 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_23		(1 << 23)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_22 Lock Region 22 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_22		(1 << 22)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_21 Lock Region 21 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_21		(1 << 21)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_20 Lock Region 20 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_20		(1 << 20)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_19 Lock Region 19 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_19		(1 << 19)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_18 Lock Region 18 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_18		(1 << 18)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_17 Lock Region 17 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_17		(1 << 17)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_16 Lock Region 16 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_16		(1 << 16)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_15 Lock Region 15 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_15		(1 << 15)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_14 Lock Region 14 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_14		(1 << 14)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_13 Lock Region 13 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_13		(1 << 13)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_12 Lock Region 12 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_12		(1 << 12)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_11 Lock Region 11 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_11		(1 << 11)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_10 Lock Region 10 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_10		(1 << 10)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_9 Lock Region 9 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_9		(1 << 9)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_8 Lock Region 8 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_8		(1 << 8)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_7 Lock Region 7 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_7		(1 << 7)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_6 Lock Region 6 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_6		(1 << 6)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_5 Lock Region 5 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_5		(1 << 5)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_4 Lock Region 4 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_4		(1 << 4)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_3 Lock Region 3 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_3		(1 << 3)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_2 Lock Region 2 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_2		(1 << 2)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_1 Lock Region 1 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_1		(1 << 1)
/** LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_0 Lock Region 0 **/
#define LOCKBIT_LOCKBIT_WORD0_LOCK_REGION_0		(1 << 0)

/**@}*/

/** @defgroup lockbit_lockbit_word1 LOCKBITWORD1 Lock Bits Word 1
@{*/

/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_63 Lock Region 63 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_63		(1 << 31)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_62 Lock Region 62 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_62		(1 << 30)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_61 Lock Region 61 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_61		(1 << 29)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_60 Lock Region 60 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_60		(1 << 28)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_59 Lock Region 59 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_59		(1 << 27)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_58 Lock Region 58 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_58		(1 << 26)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_57 Lock Region 57 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_57		(1 << 25)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_56 Lock Region 56 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_56		(1 << 24)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_55 Lock Region 55 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_55		(1 << 23)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_54 Lock Region 54 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_54		(1 << 22)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_53 Lock Region 53 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_53		(1 << 21)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_52 Lock Region 52 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_52		(1 << 20)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_51 Lock Region 51 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_51		(1 << 19)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_50 Lock Region 50 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_50		(1 << 18)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_49 Lock Region 49 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_49		(1 << 17)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_48 Lock Region 48 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_48		(1 << 16)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_47 Lock Region 47 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_47		(1 << 15)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_46 Lock Region 46 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_46		(1 << 14)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_45 Lock Region 45 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_45		(1 << 13)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_44 Lock Region 44 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_44		(1 << 12)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_43 Lock Region 43 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_43		(1 << 11)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_42 Lock Region 42 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_42		(1 << 10)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_41 Lock Region 41 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_41		(1 << 9)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_40 Lock Region 40 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_40		(1 << 8)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_39 Lock Region 39 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_39		(1 << 7)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_38 Lock Region 38 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_38		(1 << 6)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_37 Lock Region 37 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_37		(1 << 5)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_36 Lock Region 36 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_36		(1 << 4)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_35 Lock Region 35 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_35		(1 << 3)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_34 Lock Region 34 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_34		(1 << 2)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_33 Lock Region 33 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_33		(1 << 1)
/** LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_32 Lock Region 32 **/
#define LOCKBIT_LOCKBIT_WORD1_LOCK_REGION_32		(1 << 0)

/**@}*/

/** @defgroup lockbit_lockbit_word2 LOCKBITWORD2 Lock Bits Word 2
@{*/

/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_95 Lock Region 95 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_95		(1 << 31)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_94 Lock Region 94 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_94		(1 << 30)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_93 Lock Region 93 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_93		(1 << 29)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_92 Lock Region 92 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_92		(1 << 28)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_91 Lock Region 91 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_91		(1 << 27)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_90 Lock Region 90 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_90		(1 << 26)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_89 Lock Region 89 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_89		(1 << 25)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_88 Lock Region 88 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_88		(1 << 24)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_87 Lock Region 87 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_87		(1 << 23)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_86 Lock Region 86 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_86		(1 << 22)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_85 Lock Region 85 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_85		(1 << 21)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_84 Lock Region 84 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_84		(1 << 20)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_83 Lock Region 83 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_83		(1 << 19)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_82 Lock Region 82 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_82		(1 << 18)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_81 Lock Region 81 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_81		(1 << 17)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_80 Lock Region 80 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_80		(1 << 16)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_79 Lock Region 79 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_79		(1 << 15)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_78 Lock Region 78 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_78		(1 << 14)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_77 Lock Region 77 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_77		(1 << 13)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_76 Lock Region 76 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_76		(1 << 12)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_75 Lock Region 75 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_75		(1 << 11)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_74 Lock Region 74 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_74		(1 << 10)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_73 Lock Region 73 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_73		(1 << 9)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_72 Lock Region 72 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_72		(1 << 8)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_71 Lock Region 71 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_71		(1 << 7)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_70 Lock Region 70 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_70		(1 << 6)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_69 Lock Region 69 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_69		(1 << 5)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_68 Lock Region 68 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_68		(1 << 4)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_67 Lock Region 67 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_67		(1 << 3)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_66 Lock Region 66 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_66		(1 << 2)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_65 Lock Region 65 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_65		(1 << 1)
/** LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_64 Lock Region 64 **/
#define LOCKBIT_LOCKBIT_WORD2_LOCK_REGION_64		(1 << 0)

/**@}*/

/** @defgroup lockbit_lockbit_word3 LOCKBITWORD3 Lock Bits Word 3
@{*/

/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_127 Lock Region 127 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_127		(1 << 31)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_126 Lock Region 126 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_126		(1 << 30)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_125 Lock Region 125 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_125		(1 << 29)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_124 Lock Region 124 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_124		(1 << 28)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_123 Lock Region 123 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_123		(1 << 27)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_122 Lock Region 122 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_122		(1 << 26)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_121 Lock Region 121 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_121		(1 << 25)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_120 Lock Region 120 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_120		(1 << 24)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_119 Lock Region 119 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_119		(1 << 23)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_118 Lock Region 118 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_118		(1 << 22)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_117 Lock Region 117 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_117		(1 << 21)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_116 Lock Region 116 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_116		(1 << 20)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_115 Lock Region 115 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_115		(1 << 19)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_114 Lock Region 114 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_114		(1 << 18)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_113 Lock Region 113 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_113		(1 << 17)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_112 Lock Region 112 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_112		(1 << 16)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_111 Lock Region 111 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_111		(1 << 15)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_110 Lock Region 110 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_110		(1 << 14)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_109 Lock Region 109 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_109		(1 << 13)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_108 Lock Region 108 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_108		(1 << 12)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_107 Lock Region 107 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_107		(1 << 11)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_106 Lock Region 106 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_106		(1 << 10)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_105 Lock Region 105 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_105		(1 << 9)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_104 Lock Region 104 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_104		(1 << 8)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_103 Lock Region 103 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_103		(1 << 7)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_102 Lock Region 102 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_102		(1 << 6)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_101 Lock Region 101 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_101		(1 << 5)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_100 Lock Region 100 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_100		(1 << 4)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_99 Lock Region 99 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_99		(1 << 3)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_98 Lock Region 98 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_98		(1 << 2)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_97 Lock Region 97 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_97		(1 << 1)
/** LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_96 Lock Region 96 **/
#define LOCKBIT_LOCKBIT_WORD3_LOCK_REGION_96		(1 << 0)

/**@}*/
